# Generated by Django 2.2.7 on 2023-08-21 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customersupport', '0002_supportticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='created_at',
        ),
    ]
